[[colors.indexed_colors]]
color = "0xaf3a03"
index = 16

[[colors.indexed_colors]]
color = "0xd65d0e"
index = 17

[[colors.indexed_colors]]
color = "0xebdbb2"
index = 18

[[colors.indexed_colors]]
color = "0xd5c4a1"
index = 19

[[colors.indexed_colors]]
color = "0x665c54"
index = 20

[[colors.indexed_colors]]
color = "0x3c3836"
index = 21

[colors.bright]
black = "0xbdae93"
blue = "0x076678"
cyan = "0x427b58"
green = "0x79740e"
magenta = "0x8f3f71"
red = "0x9d0006"
white = "0x282828"
yellow = "0xb57614"

[colors.cursor]
cursor = "0x504945"
text = "0xfbf1c7"

[colors.normal]
black = "0xfbf1c7"
blue = "0x076678"
cyan = "0x427b58"
green = "0x79740e"
magenta = "0x8f3f71"
red = "0x9d0006"
white = "0x504945"
yellow = "0xb57614"

[colors.primary]
background = "0xfbf1c7"
foreground = "0x504945"

[cursor]
style = "Block"
unfocused_hollow = false

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 12
y = 12
